### ISSUE TITLE
[FEATURE] Add support for Jira Personal Access Token as Bearer Token

### ISSUE THREAD

**Issue by andreas-hempel** [uniqueck/asciidoctor-jira#170]
### Is your feature request related to a problem?

SSO is active in our Jira. When I try to embed Jira issues via the block macro, nothing is displayed. I have seen that Basic Auth is used in the Jira.js file. I have tried the following combination

JIRA_USERNAME: username / JIRA_APITOKEN: password
JIRA_USERNAME: username / JIRA_APITOKEN: personal access token
JIRA_USERNAME: email / JIRA_APITOKEN: password
JIRA_USERNAME: email / JIRA_APITOKEN: personal access token

I always get a 401 error from Jira.

### What solution would you like?

Is it possible that the personal access token can also be transferred as a bearer token as authentication as alternative to username:password?

lib/Jira.js constructor

```
if (jiraUserName )        
  const auth = 'Basic ' + Buffer.from(jiraUserName + ':' + jiraApiToken).toString('base64')
else if (jiraPersonalAccessToken)
  const auth = 'Bearer + jiraPersonalAccessToken
    
this.headers = {
  authorization: auth
}
```

**Comment by uniqueck** [comment]
I think this should be possible.
Do you try this at your setup?

**Comment by andreas-hempel** [comment]
I haven't tried this yet, just looked at the source code to see what the current implementation looks like.

**Comment by andreas-hempel** [comment]
I tested the call with Bearer Token via cUrl and it worked

```
curl --location 'https://ham-apjira05.europe.asklepios.net:8443/askjira/rest/api/2/search?jql=project%3DIOP%20AND%20labels%20%3D%20AP-1070' \
--header 'Authorization: Bearer personal access token'
```

**Comment by uniqueck** [comment]
I will introduce a new configuration parameter JIRA_PAT, ROADMAP_JIRA_PAT or with project key prefixed, so it is more clear for what it is used. JIRA_USERNAME and JIRA_PASSWORD / JIRA_APITOKEN will used for basic auth and personal access token for bearer authentication.

**Comment by andreas-hempel** [comment]
Hello Constantin, thank you very much for the extension. I have just installed version 4.1.0 and it works.

**Comment by uniqueck** [comment]
Hello Andreas, no problem I'm happy to see that is used in other companies. If you have other ideas let me know ;)
