### ISSUE TITLE
[FEATURE] Add support for rendering fields returned as array by Jira

### ISSUE THREAD

**Issue by lkskucera** [uniqueck/asciidoctor-jira#97]
### Is your feature request related to a problem?
Some fields from Jira may be returned as array (e.g. custom fields) - this is not covered by plugin and data are not shown.

### What solution would you like?
To add conversion of data from array before trying to convert data from object (file asciidoctor-jira.js, after line 50), such as:

```
if ( value != null && (value.constructor === Array) ) {
              value = value.toString()
            }
```

### What alternatives have you considered?
There are no alternatives if you want to be able to view the jira fields that are returned as array.

### Do you have any additional context?
I've tested the modification and it works. I apologise for not creating a pull request as I do not primary operate on a public github.

**Comment by uniqueck** [comment]
Hi @lkskucera, thanks for the issue,

do you have an example, so that I can create a test case for that modification?

Regards

**Comment by lkskucera** [comment]
Hello Constantin,
thanks for the quick response to the request.
In the attachment, there is a JSON response to some search in our Jira where several fileds are present as arrays - e.g. the customfield_14500 or even the "standard" Jira fields, such as fixVersions or issuelinks. Now looking into those arrays as some are arrays of objects, it would require a recursion to properly display JSON element string representation (e.g. when item is array of objects which are arrays...)
[search.zip](https://github.com/uniqueck/asciidoctor-jira/files/11785150/search.zip)

Kind Regards
L.

**Comment by uniqueck** [comment]
Sorry Lukas, last week was a little bit busy. Maybe this week, I will implement this stuff. I think about a more generic and customizeable way to render all kind of fields.

Constantin

**Comment by uniqueck** [comment]
Hi @lkskucera, please try version 1.1.0.

**Comment by lkskucera** [comment]
Hi, @uniqueck,
will do after holiday, thanks for quick solution !
L.

**Comment by lkskucera** [comment]
Hi @uniqueck,
I've tested the version 1.1.0 and it works. Thanks for the quick resolution of the feature 💖.
L.
